// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSg67bEmT1tZYsw7tiaLj4kpdyEXPeew8',
    appId: '1:988726282577:web:c12b9940b5e58ad4e76b70',
    messagingSenderId: '988726282577',
    projectId: 'learning-trail-64cd1',
    authDomain: 'learning-trail-64cd1.firebaseapp.com',
    storageBucket: 'learning-trail-64cd1.firebasestorage.app',
    measurementId: 'G-ZKJXS9L9Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADnucDUW30M-ax9mQqRSjyCi8hOdVRbgM',
    appId: '1:988726282577:android:fb4c165f37ae8edae76b70',
    messagingSenderId: '988726282577',
    projectId: 'learning-trail-64cd1',
    storageBucket: 'learning-trail-64cd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-IpM7LLpSHAeabIfNkzs-t4zYid_4zpc',
    appId: '1:988726282577:ios:08532266b4ddd5b5e76b70',
    messagingSenderId: '988726282577',
    projectId: 'learning-trail-64cd1',
    storageBucket: 'learning-trail-64cd1.firebasestorage.app',
    iosClientId: '988726282577-k47sjdurkokpfpriqeoiq0u7e4fbnlkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningtrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-IpM7LLpSHAeabIfNkzs-t4zYid_4zpc',
    appId: '1:988726282577:ios:08532266b4ddd5b5e76b70',
    messagingSenderId: '988726282577',
    projectId: 'learning-trail-64cd1',
    storageBucket: 'learning-trail-64cd1.firebasestorage.app',
    iosClientId: '988726282577-k47sjdurkokpfpriqeoiq0u7e4fbnlkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningtrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSg67bEmT1tZYsw7tiaLj4kpdyEXPeew8',
    appId: '1:988726282577:web:d683adb1340b6986e76b70',
    messagingSenderId: '988726282577',
    projectId: 'learning-trail-64cd1',
    authDomain: 'learning-trail-64cd1.firebaseapp.com',
    storageBucket: 'learning-trail-64cd1.firebasestorage.app',
    measurementId: 'G-Y4066RDLV8',
  );
}
