import { StoreData } from "@/store";
import { sql } from "drizzle-orm";
import { jsonb, pgTable, timestamp, uuid, varchar } from "drizzle-orm/pg-core";

export const usersTable = pgTable("users", {
  id: uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`), // generated by server
  shortId: varchar("short_id", { length: 255 }).notNull(), // generated by app
  email: varchar("email", { length: 255 }).notNull(),
  password: varchar("password", { length: 255 }).notNull(), // hashed
  data: jsonb("data").$type<StoreData>().default({}).notNull(),
});

export const sessionsTable = pgTable("sessions", {
  id: uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`), // generated by app
  accountId: uuid("account_id").references(() => usersTable.id), // if null, not logged in
  createdAt: timestamp("created_at").defaultNow().notNull(),
  expiresAt: timestamp("expires_at").notNull(),
});
